name: Lint (pylint) and Type Check (mypy)

on:
  push:
    branches:
      - dev

jobs:
  lint-and-type-checks:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy
    - name: Run Pylint and check score
      run: |
        # python -m pylint **/*.py

        # Run pylint and save the output, allowing all exit codes
        pylint_output=$(pylint **/*.py || true)

        # Output pylint results to the GitHub Actions log
        echo "$pylint_output"

        # Extract the pylint score
        pylint_score=$(echo "$pylint_output" | grep -oP "Your code has been rated at \K[0-9]*\.[0-9]*/10" | grep -oP "[0-9]*\.[0-9]*" | head -n 1)

        # Check if the pylint score is greater than 7
        if (( $(echo "$pylint_score > 7" | bc -l) )); then
          echo "Pylint score is greater than 7: $pylint_score"
          exit 0  # Exit successfully if score is above 7
        else
          echo "Pylint score is not greater than 7: $pylint_score"
          exit 1  # Fail the workflow if score is 7 or below
        fi
    - name: Type check with Mypy
      run: mypy .